local L={}
local function add(key,en,cn,tw) L["native_"..key]={en=en,["zh-cn"]=cn,["zh-tw"]=tw or cn} end
add("language","en","cn","tw")
add("coarse_intro","Drag to select a level · Click the number to type","拖动选择档位 · 点击数值输入","拖曳選擇檔位 · 點選數值輸入")
add("reset_all","Reset HCM multipliers","重置 HCM 全部倍率","重設 HCM 全部倍率")
add("reset","Reset to 1×","恢复 1×","恢復 1×")
add("yes","Yes","是"); add("no","No","否"); add("enabled","Enabled","启用","啟用")
add("invalid","Change rejected: %s","修改未保存：%s","修改未儲存：%s")
add("minimum","Minimum","最小值"); add("maximum","Maximum","最大值")
add("composition_help","Each row is one breed with a native minimum–maximum count. Roles follow this source's existing composition.","每行对应一种兵种及原版数量范围；可选兵种遵循当前来源已有的兵种类型。","每行對應一種兵種及原版數量範圍；可選兵種遵循目前來源已有的兵種類型。")
add("pool_help","Preserves the native list order and duplicate entries. Different sources use lists differently; these are not universal weights.","保留原版列表顺序与重复项。各来源对列表的用法不同，这里不将重复项视为通用权重。","保留原版清單順序與重複項。各來源對清單的用法不同，這裡不將重複項視為通用權重。")
add("add_entry","Add an entry","添加编成行","新增編成列")
add("up","‹ Parent group","‹ 返回上级","‹ 返回上層")
add("choose_field","Open a group, then select a native field. Template paths identify the precise difficulty, faction or tactic being edited.","展开分组后选择具体字段。模板路径用于区分正在编辑的难度、阵营或战术。","展開群組後選擇具體欄位。模板路徑用於區分正在編輯的難度、陣營或戰術。")
add("baseline","Native template value: %s","原版模板值：%s")
add("preview_help","Shown values include HCM multipliers and saved HED overrides. The game applies its condition modifiers and placement limits afterward. Changes apply next mission.","显示值包含 HCM 倍率及 HED 覆盖。游戏随后仍会应用词条修正及放置限制。修改在下一局生效。","顯示值包含 HCM 倍率及 HED 覆蓋。遊戲隨後仍會套用詞條修正及放置限制。修改在下一局生效。")
add("mission_budget_help","Node budgets shown here precede the native difficulty and condition modifiers. HCM's event-budget multiplier scales the final budget and its native cap. Changes apply next mission.","此处显示节点基础预算。游戏先应用难度与词条修正，HCM 事件预算倍率再调整最终预算及原版预算封顶。修改在下一局生效。","此處顯示節點基礎預算。遊戲先套用難度與詞條修正，HCM 事件預算倍率再調整最終預算及原版預算上限。修改在下一局生效。")
add("reset_override","Remove override • follow HCM","删除覆盖 · 跟随 HCM","移除覆蓋 · 跟隨 HCM")
add("use_native","Override with native value","固定为原版模板值","固定為原版模板值")
add("encounter_start","Eligibility for new encounters","新遭遇启动条件","新遭遇啟動條件")
add("no_rules","This template has no supported condition entry point. Its existing numeric and composition fields remain available in the other tabs.","此模板没有可用的条件入口。其已有数值和编成字段仍可在其他标签页调整。","此模板沒有可用的條件入口。其已有數值和編成欄位仍可在其他分頁調整。")
add("reset_rule","Restore native conditions","恢复原版条件","恢復原版條件")
add("append","Keep native conditions + add this rule","保留原版条件，并附加本规则","保留原版條件，並附加本規則")
add("replace","Replace this predicate list","替换此条件函数列表","取代此條件函式清單")
add("all","All clauses must pass","满足全部条件","滿足全部條件")
add("any","At least one clause must pass","满足任一条件","滿足任一條件")
add("value","Value","阈值","閾值")
add("add_condition","Add a condition clause","添加触发条件","新增觸發條件")
add("rules_help","Up to 8 clauses. Replacement is available only for native coordinated-horde predicate lists. Physical spawn limits and mission flow stay native.","最多 8 个条件。仅协同尸潮的原版条件函数列表支持替换；出生位置限制和任务流程仍由原版控制。","最多 8 個條件。僅協同屍潮的原版條件函式清單支援取代；出生位置限制和任務流程仍由原版控制。")
add("no_templates","No supported native templates in this category.","此分类没有可编辑的原版模板。","此分類沒有可編輯的原版模板。")
add("family_pacing","Combat pacing & heat","战斗节奏与热度","戰鬥節奏與熱度")
add("family_roamers","Map population","地图敌群","地圖敵群")
add("family_hordes","Hordes & trickle waves","尸潮与小股潮","屍潮與小股潮")
add("family_specials","Specialist scheduling","特感调度","特感調度")
add("family_monsters","Monsters & patrols","怪物与精英巡逻队","怪物與精英巡邏隊")
add("family_events","Automatic combat events","自动战斗事件","自動戰鬥事件")
add("family_mutators","Condition mechanics","词条机制","詞條機制")
add("family_mission_events","Mission combat nodes","任务战斗节点","任務戰鬥節點")
add("tab_parameters","Parameters","参数","參數")
add("tab_composition","Composition & weights","编成与权重","編成與權重")
add("tab_rules","Trigger conditions","触发条件","觸發條件")
add("tab_presets","Preset library","方案库","方案庫")
add("choice_ahead","Ahead","前方"); add("choice_behind","Behind","后方","後方")
add("choice_build_up_tension_low","Low build-up","低压积累","低壓累積")
add("choice_build_up_tension","Build-up","压力积累","壓力累積")
add("choice_build_up_tension_high","High build-up","高压积累","高壓累積")
add("choice_sustain_tension_peak","Sustained peak","保持压力峰值","保持壓力峰值")
add("choice_tension_peak_fade","Peak fading","压力回落","壓力回落")
add("choice_relax","Recovery","恢复","恢復")
add("seed","Map seed (0 = mission)","地图种子（0 跟随任务）","地圖種子（0 跟隨任務）")
add("difficulty","Difficulty table %s","难度表 %s","難度表 %s")
add("whole_template","Whole native template","完整原版模板")
add("by_faction","by faction","按阵营选择","依陣營選擇")
add("preset_summary","%d field overrides • %d trigger rules\nHCM multipliers and map seed are included. Native templates are read from the installed game.","%d 项字段覆盖 · %d 项触发规则\n包含 HCM 倍率和地图种子；原版模板始终从当前游戏读取。","%d 項欄位覆蓋 · %d 項觸發規則\n包含 HCM 倍率和地圖種子；原版模板始終從目前遊戲讀取。")
L.ui_036={en="Overall tuning",["zh-cn"]="整体调节",["zh-tw"]="整體調節"}
L.ui_037={en="Detailed tuning",["zh-cn"]="详细调节",["zh-tw"]="詳細調節"}
L.ui_049={en="General",["zh-cn"]="通用",["zh-tw"]="通用"}
L.ui_072={en="Saved automatically • Changes apply next mission",["zh-cn"]="自动保存 · 下一局生效",["zh-tw"]="自動儲存 · 下一局生效"}
add("unit_seconds","seconds","秒")
add("unit_meters","meters","米","公尺")
add("unit_percent","0–1","0–1")
add("unit_multiplier","multiplier","倍数","倍數")
L.ui_051={en="Imported from SoloPlay. Click to add or remove. Shared effects load once; game replacement rules still apply.",["zh-cn"]="词条从 SoloPlay 导入。点击添加或删除；相同机制只加载一次，仍遵循游戏自身的覆盖规则。",["zh-tw"]="詞條從 SoloPlay 匯入。點選新增或移除；相同機制只載入一次，仍遵循遊戲自身的覆蓋規則。"}
add("mixed","Custom","自定义","自訂")
add("global_help","Levels 1–10 increase ordinary enemies gradually and elite, specialist and boss pressure more strongly. Level 1 keeps native spawn multipliers when HED is also at baseline. Rear-enemy and patrol recycling is automatic at every level.\n\nLevel 10: route population 1.5×, ordinary wave size 1.25×, elite members 3×, patrol encounters 6×, map monsters 8×, specialist capacity 3× and refill 3.25×. Coordinated load ceiling: 105. Actual arrivals still depend on pacing and positions.\n\nSelecting a level replaces all 20 HCM controls. Individual controls are in Advanced settings; HED overrides remain.","1～10 档让普通敌人缓慢增加，精英、特感和 Boss 投入增长更快。HED 也没有额外覆盖时，1 档保留原版生成倍率；所有档位均自动回收符合条件的后方敌人与巡逻队。\n\n10 档：沿途人数 1.5×、单波普通人数 1.25×、精英人数 3×、巡逻次数 6×、地图怪物 8×、特感容量 3×、补充频率 3.25×；协同负荷上限 105。实际到场仍取决于调度与点位。\n\n选档会替换全部 20 项 HCM 数值，单项控件位于高级设置，HED 覆盖保留。","1～10 檔讓普通敵人緩慢增加，精英、特感和 Boss 投入增長更快。HED 也沒有額外覆蓋時，1 檔保留原版生成倍率；所有檔位均自動回收符合條件的後方敵人與巡邏隊。\n\n10 檔：沿途人數 1.5×、單波普通人數 1.25×、精英人數 3×、巡邏次數 6×、地圖怪物 8×、特感容量 3×、補充頻率 3.25×；協同負荷上限 105。實際到場仍取決於排程與點位。\n\n選檔會替換全部 20 項 HCM 數值，單項控制元件位於高階設定，HED 覆蓋保留。")
add("intensity_value","Level %d","%d 档","%d 檔")
add("profile_summary","Elite patrols %.4g×   ·   Bosses %.4g×   ·   Specialist capacity %.4g×   ·   Refill %.4g×","精英巡逻 %.4g×   ·   Boss %.4g×   ·   特感容量 %.4g×   ·   补充频率 %.4g×","精英巡邏 %.4g×   ·   Boss %.4g×   ·   特感容量 %.4g×   ·   補充頻率 %.4g×")
add("advanced_open","+ Advanced settings","+ 高级设置","+ 進階設定")
add("advanced_close","− Advanced settings","− 高级设置","− 進階設定")
return L
