"""Embed the editable template packages as a hidden, lazy-loaded Lua module."""
from pathlib import Path
import json

PROJECT = Path(__file__).resolve().parents[1]
SOURCE = PROJECT / 'custom-packages/template-library'
# Other editable examples are development material, not built-in conditions.
BUILTIN = ('starter-conditions-frenzied_assault', 'starter-conditions-no_healing')
OUTPUT = PROJECT / 'src/HavocConditionManager/scripts/mods/HavocConditionManager/diy/diy_template_packages.lua'


def lua_string(value):
    separator = '='
    while ']' + separator + ']' in value:
        separator += '='
    return '[' + separator + '[' + value + ']' + separator + ']'


def build():
    lines = ['-- Generated by tools/build_diy_templates.py. Extracted only by an explicit UI action.', 'return {']
    count = 0
    for package_id in BUILTIN:
        folder = SOURCE / package_id
        manifest = json.loads((folder / 'package.json').read_text(encoding='utf-8-sig'))
        assert manifest['id'] == folder.name
        lines.append('    [' + json.dumps(folder.name) + ']={')
        names = ['package.json'] + manifest['files']
        for name in names:
            value = (folder / name).read_text(encoding='utf-8-sig')
            lines.append('        [' + json.dumps(name) + ']=' + lua_string(value) + ',')
        lines.append('    },')
        count += 1
    lines.append('}\n')
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Embedded {count} template packages ({OUTPUT.stat().st_size} bytes)')


if __name__ == '__main__':
    build()
