-- Generated by tools/build_diy_templates.py. Extracted only by an explicit UI action.
return {
    ["starter-conditions-frenzied_assault"]={
        ["package.json"]=[=[{
  "format": "Darktide.DIY.Package",
  "version": 2,
  "id": "starter-conditions-frenzied_assault",
  "entry_namespace": "starter-conditions",
  "package_version": "2.2.1",
  "kind": "conditions",
  "api": {
    "major": 1,
    "min_minor": 0
  },
  "name": {
    "en": "Frenzied assault",
    "zh-cn": "狂暴攻势",
    "zh-tw": "狂暴攻勢"
  },
  "description": {
    "zh-cn": "全体敌人的常规近战攻击速度与动画播放速度 +20%，同步命中、连击、扫击与动作时长。仅支持本地单人/机器人房间；需要安装随附的近战动画资源。",
    "zh-tw": "全體敵人的常規近戰攻擊速度與動畫播放速度 +20%，同步命中、連擊、掃擊與動作時長。僅支援本地單人/機器人房間；需要安裝隨附的近戰動畫資源。",
    "en": "+20% ordinary enemy melee attack and animation speed, with matching hit, combo, sweep and end timings. Local solo/bot sessions only; install the included melee animation resources."
  },
  "definitions": "definitions.json",
  "entrypoint": "lua/main.lua",
  "files": [
    "definitions.json",
    "lua/main.lua",
    "lua/legacy_cleanup.lua",
    "lua/timing.lua",
    "lua/resources.lua"
  ],
  "capabilities": [
    "native.v1",
    "cleanup.v1"
  ]
}
]=],
        ["definitions.json"]=[=[{
  "format": "Darktide.DIY",
  "version": 1,
  "kind": "conditions",
  "id": "starter-conditions",
  "name": {
    "en": "Frenzied assault",
    "zh-cn": "狂暴攻势",
    "zh-tw": "狂暴攻勢"
  },
  "entries": [
    {
      "id": "frenzied_assault",
      "name": {
        "en": "Frenzied assault",
        "zh-cn": "狂暴攻势",
        "zh-tw": "狂暴攻勢"
      },
      "description": {
        "zh-cn": "全体敌人的常规近战攻击速度与动画播放速度 +20%，同步命中、连击、扫击与动作时长。仅支持本地单人/机器人房间；需要安装随附的近战动画资源。",
        "zh-tw": "全體敵人的常規近戰攻擊速度與動畫播放速度 +20%，同步命中、連擊、掃擊與動作時長。僅支援本地單人/機器人房間；需要安裝隨附的近戰動畫資源。",
        "en": "+20% ordinary enemy melee attack and animation speed, with matching hit, combo, sweep and end timings. Local solo/bot sessions only; install the included melee animation resources."
      },
      "enabled": true,
      "tier": 3,
      "weight": 1,
      "targets": {
        "kind": "minions"
      },
      "conditions": [],
      "match": "all",
      "rules": [],
      "script": true
    }
  ]
}
]=],
        ["lua/main.lua"]=[=[-- Native-controller melee acceleration. Matching animation resources are
-- required; this implementation supports local solo/bot sessions.
local mod=get_mod("HavocConditionManager")
local Timing=require("./timing.lua")
local Resource=require("./resources.lua")
local Melee=require("scripts/extension_systems/behavior/nodes/actions/bt_melee_attack_action")
local function weak()return setmetatable({},{__mode="k"})end
local function local_session()
    if not mod.has_local_gameplay_authority() then return false end
    for _,player in pairs(Managers.player:human_players())do
        if player.remote then return false end
    end
    return true
end
local function restore(driver,unit,record)
    if ALIVE[unit] then
        for i,index in ipairs(record.indices)do
            -- Do not undo an independent subsequent variable change.
            local current=Unit.animation_get_variable(unit,index)
            if math.abs(current-record.values[i])<0.000001 then
                Unit.animation_set_variable(unit,index,record.defaults[i])
            end
        end
    end
    driver.units[unit]=nil
end
local function bind(driver,unit)
    local existing=driver.units[unit]
    if existing and existing.rate==driver.timing.rate then return existing end
    if existing then restore(driver,unit,existing)end
    if driver.unsupported[unit] then return end
    if not Unit.has_animation_state_machine(unit) then return end
    local record={indices={},defaults={},values={},rate=driver.timing.rate,pad=setmetatable({},{__mode="v"})}
    -- One bounded discovery when this enemy first attacks. Native playback
    -- then consumes the variables; no timer, layer scan, or raw memory access.
    for _,v in ipairs(driver.resource.variables)do
        local ok,index=pcall(Unit.animation_find_variable,unit,v.name)
        if ok and type(index)=="number" and index>=0 and index<256 and index%1==0 then
            local current=Unit.animation_get_variable(unit,index)
            if type(current)~="number" or current~=current or math.abs(current-v.default)>0.000001 then
                driver.unsupported[unit]=true;return
            end
            record.indices[#record.indices+1]=index
            record.defaults[#record.defaults+1]=current
            record.values[#record.values+1]=current*driver.timing.rate
        end
    end
    if #record.indices==0 then driver.unsupported[unit]=true;return end
    -- Discovery is transactional: a missing/conflicting variable never leaves
    -- a partially changed unit or advances only its damage timings.
    for i,index in ipairs(record.indices)do
        Unit.animation_set_variable(unit,index,record.values[i])
    end
    driver.units[unit]=record
    return record
end
local installed_driver
local function install()
    if installed_driver then return installed_driver end
    local driver=mod._diy_native_melee_20
    driver=driver or {units=weak(),cache=weak(),unsupported=weak()}
    mod._diy_native_melee_20=driver
    -- Replace this mod's three handlers once per freshly loaded module. Keep
    -- the shared driver so an old in-flight swing can drain on its own times.
    -- DMF replaces handlers in place; refresh does not add another hook layer.
    local dmf=get_mod("DMF")
    local previous=mod:get_internal_data("allow_rehooking")
    dmf.set_internal_data(mod,"allow_rehooking",true)
    local ok,why=pcall(function()
    mod:hook(Melee,"enter",function(fn,self,unit,breed,blackboard,pad,data,t,...)
        pad._hcm_native_melee_data=nil
        local session=Managers.state and Managers.state.game_session
        if driver.enabled and driver.session==session and local_session() then
            local record=bind(driver,unit)
            if record then
                local prepared=driver.cache[data]
                if not prepared then
                    prepared=driver.timing.prepare(data,driver.resource.events)
                    driver.cache[data]=prepared
                end
                pad._hcm_native_melee_data=prepared
                record.pad[1]=pad
                data=prepared
            end
        elseif driver.units[unit] then
            restore(driver,unit,driver.units[unit])
        end
        return fn(self,unit,breed,blackboard,pad,data,t,...)
    end)
    mod:hook(Melee,"run",function(fn,self,unit,breed,blackboard,pad,data,dt,t,...)
        -- One field selection; all updates, collisions, and animations remain
        -- native. Needed to keep later combo impact FX on the prepared times.
        return fn(self,unit,breed,blackboard,pad,pad._hcm_native_melee_data or data,dt,t,...)
    end)
    mod:hook(Melee,"leave",function(fn,self,unit,breed,blackboard,pad,data,t,...)
        fn(self,unit,breed,blackboard,pad,pad._hcm_native_melee_data or data,t,...)
        pad._hcm_native_melee_data=nil
        local record=driver.units[unit]
        if record and record.pad[1]==pad then
            record.pad[1]=nil
            if not driver.enabled or driver.session~=Managers.state.game_session or not local_session() then
                restore(driver,unit,record)
            end
        end
    end)
    end)
    dmf.set_internal_data(mod,"allow_rehooking",previous)
    assert(ok,why)
    installed_driver=driver
    return driver
end
local function activate(ctx)
    assert(local_session(),"原生近战 +20% 仅支持本地单人/机器人房间。")
    assert(Unit.animation_find_variable and Unit.animation_set_variable,
        "当前引擎没有所需的原生动画变量接口。")
    require("./legacy_cleanup.lua")()
    local driver=install()
    driver.timing=Timing;driver.resource=Resource;driver.cache=weak();driver.unsupported=weak()
    driver.enabled=true;driver.session=Managers.state.game_session;driver.owner=ctx
    ctx:on_cleanup(function()
        if driver.owner~=ctx then return end
        driver.enabled=false;driver.owner=nil;driver.cache=weak();driver.unsupported=weak()
        -- Let an in-progress swing complete on its matching animation/timing
        -- pair. Its native leave callback restores the variables afterwards.
        for unit,record in pairs(driver.units)do
            if not record.pad[1] then restore(driver,unit,record)end
        end
    end)
end
return {api_version={major=1,minor=0},entries={frenzied_assault={on_activate=activate}}}
]=],
        ["lua/legacy_cleanup.lua"]=[=[-- Migration only. Never load/install the retired native driver or read memory.
return function()
    local mod=get_mod("HavocConditionManager")
    local previous=mod._diy_frenzied_assault_hooks_v1
    assert(not (previous and previous.current and previous.current.active),
        "Finish the active mission before replacing Frenzied assault")
    local saved=mod:persistent_table("diy_frenzy_native_timestep_v1")
    if saved.driver then
        local ok,why=saved.driver:disable()
        assert(ok~=false,"Retired animation hook cleanup failed: "..tostring(why))
    end
    if not previous and not mod._diy_frenzied_retired_hooks then return end
    local actions="scripts/extension_systems/behavior/nodes/actions/"
    for _,spec in ipairs({
        {"scripts/extension_systems/behavior/ai_brain","update"},
        {actions.."bt_melee_attack_action","_start_attack_anim"},
        {actions.."bt_chaos_hound_leap_action","_check_leap_for_collisions"},
        {actions.."bt_leap_action","_check_leap_for_collisions"},
        {"scripts/extension_systems/locomotion/minion_locomotion_extension","set_wanted_velocity"},
        {"scripts/extension_systems/locomotion/minion_locomotion_extension","set_wanted_velocity_flat"},
        {"scripts/utilities/minion_attack","start_shooting"},
        {"scripts/foundation/utilities/script_world","update"},
    })do mod:hook_disable(require(spec[1]),spec[2])end
    mod._diy_frenzied_assault_hooks_v1=nil
    mod._diy_frenzied_retired_hooks=true
    -- Keep the disabled driver's storage pinned until process exit.
end
]=],
        ["lua/timing.lua"]=[=[-- Prepare once per native action definition; retain all non-timing values.
-- The returned tables are private to this package, including combo windows.
local T={rate=1.2}
local event_fields={
    "attack_anim_durations","attack_anim_damage_timings","move_start_timings",
    "melee_attack_rotation_durations","effect_template_start_timings",
    "disable_shield_block_timing","enable_shield_block_timing",
}
local function times(value)
    if type(value)=="number" then return value/T.rate end
    if type(value)~="table" then return value end
    local out={}
    for k,v in pairs(value)do out[k]=times(v)end
    return out
end
local function sweep(value)
    local out={}
    for k,v in pairs(value)do out[k]=v end
    if type(value[1])=="table" then
        for i,window in ipairs(value)do out[i]=sweep(window)end
    else
        -- A third field is a sweep node override, not a duration.
        out[1]=value[1]/T.rate;out[2]=value[2]/T.rate
    end
    return out
end
local function events(source,supported,transform)
    local out={}
    for event,value in pairs(source)do
        out[event]=supported[event] and transform(value) or value
    end
    return out
end
function T.prepare(source,supported)
    local out={}
    for k,v in pairs(source)do out[k]=v end
    for _,key in ipairs(event_fields)do
        if source[key] then out[key]=events(source[key],supported,times)end
    end
    if source.attack_sweep_damage_timings then
        out.attack_sweep_damage_timings=events(source.attack_sweep_damage_timings,supported,sweep)
    end
    local impact=source.sweep_ground_impact_fx_timing
    if type(impact)=="table" then out.sweep_ground_impact_fx_timing=events(impact,supported,times)
    elseif impact then out.sweep_ground_impact_fx_timing=impact/T.rate end
    return out
end
return T
]=],
        ["lua/resources.lua"]=[=[-- Generated from verified local controller operands; no per-breed runtime table.
return {variables={
    {name="hcm_melee_3f800000",default=1.0},
    {name="hcm_melee_3f8ccccd",default=1.100000023841858},
    {name="hcm_melee_3f900000",default=1.125},
    {name="hcm_melee_3f933333",default=1.149999976158142},
    {name="hcm_melee_3f99999a",default=1.2000000476837158},
    {name="hcm_melee_3fa00000",default=1.25},
    {name="hcm_melee_3fa66666",default=1.2999999523162842},
    {name="hcm_melee_3faccccd",default=1.350000023841858},
    {name="hcm_melee_3fb33333",default=1.399999976158142},
    {name="hcm_melee_3fb9999a",default=1.4500000476837158},
    {name="hcm_melee_3fc00000",default=1.5},
    {name="hcm_melee_3fc66666",default=1.5499999523162842},
    {name="hcm_melee_3fcccccd",default=1.600000023841858},
    {name="hcm_melee_40000000",default=2.0},
},events={
    ["attack_01"]=true,
    ["attack_02"]=true,
    ["attack_03"]=true,
    ["attack_04"]=true,
    ["attack_05"]=true,
    ["attack_06"]=true,
    ["attack_07"]=true,
    ["attack_08"]=true,
    ["attack_2h_pommel"]=true,
    ["attack_bayonet_01"]=true,
    ["attack_bayonet_02"]=true,
    ["attack_bayonet_04"]=true,
    ["attack_bayonet_05"]=true,
    ["attack_body_slam"]=true,
    ["attack_catapult"]=true,
    ["attack_combo"]=true,
    ["attack_combo_01"]=true,
    ["attack_combo_04"]=true,
    ["attack_combo_08"]=true,
    ["attack_combo_2"]=true,
    ["attack_combo_3"]=true,
    ["attack_combo_standing_06"]=true,
    ["attack_down"]=true,
    ["attack_down_01"]=true,
    ["attack_ground_slam"]=true,
    ["attack_heavy_swing"]=true,
    ["attack_heavy_swing_fast"]=true,
    ["attack_heavy_swing_fast_02"]=true,
    ["attack_heavy_swing_moving"]=true,
    ["attack_kick_01"]=true,
    ["attack_kick_02"]=true,
    ["attack_knee_01"]=true,
    ["attack_melee_claw"]=true,
    ["attack_melee_claw_02"]=true,
    ["attack_melee_combo"]=true,
    ["attack_melee_combo_2"]=true,
    ["attack_melee_combo_3"]=true,
    ["attack_melee_combo_4"]=true,
    ["attack_move_01"]=true,
    ["attack_move_02"]=true,
    ["attack_move_03"]=true,
    ["attack_move_04"]=true,
    ["attack_move_combo_01_fast"]=true,
    ["attack_move_combo_04_fast"]=true,
    ["attack_move_combo_08_fast"]=true,
    ["attack_pommel_01"]=true,
    ["attack_pommel_02"]=true,
    ["attack_pommel_03"]=true,
    ["attack_push_01"]=true,
    ["attack_push_kick_01"]=true,
    ["attack_push_punch_01"]=true,
    ["attack_push_punch_02"]=true,
    ["attack_push_punch_03"]=true,
    ["attack_push_punch_04"]=true,
    ["attack_push_punch_05"]=true,
    ["attack_push_punch_06"]=true,
    ["attack_reach_up"]=true,
    ["attack_reach_up_01"]=true,
    ["attack_run_01"]=true,
    ["attack_run_02"]=true,
    ["attack_run_03"]=true,
    ["attack_slam"]=true,
    ["attack_slam_left"]=true,
    ["attack_slam_right"]=true,
    ["attack_standing_combo"]=true,
    ["attack_stomp"]=true,
    ["attack_swing_combo_02"]=true,
    ["attack_swing_combo_03"]=true,
    ["attack_swing_combo_04"]=true,
    ["attack_swing_combo_05"]=true,
    ["attack_sword_combo"]=true,
    ["attack_tail_slam"]=true,
    ["attack_tail_whip_left"]=true,
    ["attack_tail_whip_right"]=true,
    ["attack_turn_bwd"]=true,
    ["attack_turn_left"]=true,
    ["attack_turn_right"]=true,
    ["attack_up"]=true,
    ["bayonet_attack_stab"]=true,
    ["bayonet_attack_stab_02"]=true,
    ["bayonet_attack_sweep"]=true,
    ["bayonet_attack_sweep_02"]=true,
    ["bayonet_charge_hit"]=true,
    ["bayonet_charge_hit_02"]=true,
    ["bayonet_charge_hit_03"]=true,
    ["bayonet_charge_hit_04"]=true,
    ["bayonet_charge_hit_05"]=true,
    ["cultist_captain_heavy"]=true,
    ["cultist_heavy_slam"]=true,
    ["move_attack_06"]=true,
    ["move_attack_07"]=true,
    ["move_attack_09"]=true,
    ["move_attack_cleave"]=true,
    ["move_attack_cleave_02"]=true,
    ["move_attack_cleave_03"]=true,
    ["move_attack_cleave_04"]=true,
    ["shield_push"]=true,
}}
]=],
    },
    ["starter-conditions-no_healing"]={
        ["package.json"]=[=[{
  "api": {
    "major": 1,
    "min_minor": 0
  },
  "definitions": "definitions.json",
  "description": {
    "en": "Keep stations whose batteries start plugged in, with zero charges. Remove empty-socket stations and their nearby batteries. Medical stims and medical crates do not spawn; other healing remains available.",
    "zh-cn": "开局电池已经插入的医疗站予以保留，但可用次数设为 0。开局电池舱为空、需要从附近搬运电池的医疗站，会连同配套电池一起移除。地图不再刷新医疗针剂和医疗包；技能、天赋等其他治疗仍可使用。已携带物品的正常丢弃不受这项地图刷新限制影响。",
    "zh-tw": "開局電池已經插入的醫療站予以保留，但可用次數設為 0。開局電池艙為空、需要從附近搬運電池的醫療站，會連同配套電池一起移除。地圖不再重新整理醫療針劑和醫療包；技能、天賦等其他治療仍可使用。已攜帶物品的正常丟棄不受這項地圖重新整理限制影響。"
  },
  "entry_namespace": "starter-conditions",
  "files": [
    "definitions.json",
    "lua/main.lua"
  ],
  "format": "Darktide.DIY.Package",
  "id": "starter-conditions-no_healing",
  "kind": "conditions",
  "name": {
    "en": "No healing",
    "zh-cn": "禁止治疗",
    "zh-tw": "禁止治療"
  },
  "package_version": "1.2.0",
  "shared_signals": [
    "diy_pressure"
  ],
  "version": 2,
  "entrypoint": "lua/main.lua",
  "capabilities": [
    "native.v1",
    "cleanup.v1"
  ]
}
]=],
        ["definitions.json"]=[=[{
  "description": {
    "en": "Apply the native keyword that prevents healing.",
    "zh-cn": "应用原生禁止治疗关键词；不替换敌人或增加任务事件。",
    "zh-tw": "應用原生禁止治療關鍵詞；不替換敵人或增加任務事件。"
  },
  "entries": [
    {
      "conditions": [],
      "description": {
        "en": "Keep stations whose batteries start plugged in, with zero charges. Remove empty-socket stations and their nearby batteries. Medical stims and medical crates do not spawn; other healing remains available.",
        "zh-cn": "开局电池已经插入的医疗站予以保留，但可用次数设为 0。开局电池舱为空、需要从附近搬运电池的医疗站，会连同配套电池一起移除。地图不再刷新医疗针剂和医疗包；技能、天赋等其他治疗仍可使用。已携带物品的正常丢弃不受这项地图刷新限制影响。",
        "zh-tw": "開局電池已經插入的醫療站予以保留，但可用次數設為 0。開局電池艙為空、需要從附近搬運電池的醫療站，會連同配套電池一起移除。地圖不再重新整理醫療針劑和醫療包；技能、天賦等其他治療仍可使用。已攜帶物品的正常丟棄不受這項地圖重新整理限制影響。"
      },
      "enabled": true,
      "id": "no_healing",
      "match": "all",
      "name": {
        "en": "No healing",
        "zh-cn": "禁止治疗",
        "zh-tw": "禁止治療"
      },
      "rules": [],
      "source_row": 46,
      "targets": {
        "kind": "players"
      },
      "tier": 4,
      "weight": 1,
      "script": true
    }
  ],
  "format": "Darktide.DIY",
  "id": "starter_conditions",
  "kind": "conditions",
  "name": {
    "en": "No healing",
    "zh-cn": "禁止治疗",
    "zh-tw": "禁止治療"
  },
  "version": 1
}
]=],
        ["lua/main.lua"]=[=[-- Local authority only. Keep initially plugged medicae empty; remove the
-- unpowered station/battery pair. Do not modify general healing or quest batteries.
local mod = get_mod("HavocConditionManager")
local HealthStation = require("scripts/extension_systems/health_station/health_station_extension")
local HealthStationSystem = require("scripts/extension_systems/health_station/health_station_system")
local PickupSystem = require("scripts/extension_systems/pickups/pickup_system")
local Pocketable = require("scripts/utilities/pocketable")

local blocked_pickups = {
    syringe_corruption_pocketable = true,
    medical_crate_pocketable = true,
}

local function pack(...)
    return { n = select("#", ...), ... }
end

local function controller(state, server)
    local current = state.current
    if current and current.active and server ~= false and mod.has_local_gameplay_authority()
        and Managers.state and Managers.state.game_session == current.session then
        return current
    end
end

local function transfer(current, fn, ...)
    current.transfer_depth = current.transfer_depth + 1
    local results = pack(pcall(fn, ...))
    current.transfer_depth = current.transfer_depth - 1
    if not results[1] then error(results[2], 0) end
    return unpack(results, 2, results.n)
end

local function install_hooks()
    -- DMF registers one handler per mod/method. Retain only a routing table
    -- between missions so a refreshed package can supply a new controller.
    local state = mod._diy_medical_map_hooks_v1
    if state then return state end
    state = {}
    mod._diy_medical_map_hooks_v1 = state

    mod:hook(HealthStation, "fixed_update", function(fn, self, ...)
        local current = controller(state, self._is_server)
        if not current then return fn(self, ...) end
        local decision = current:station_kind(self)
        if decision == "remove" then
            current.pending[self._unit] = self
            return
        end
        if current.cleared[self] then return fn(self, ...) end
        self._distributed_charges = 0
        local results = pack(fn(self, ...))
        current:empty_station(self)
        return unpack(results, 1, results.n)
    end)

    mod:hook(HealthStation, "spawn_battery", function(fn, self, ...)
        local current = controller(state, self._is_server)
        if current and not self._first_frame_setup and self:use_distribution_pool()
            and self._distributed_charges == nil then
            -- A component flow can run before distribution. Defer this spawn
            -- to native first-frame setup instead of caching an empty-socket
            -- decision before the station's placement has been assigned.
            return
        end
        if current and current:station_kind(self) == "remove" then
            current.pending[self._unit] = self
            return
        end
        return fn(self, ...)
    end)

    mod:hook(HealthStationSystem, "hot_join_sync", function(fn, self, sender, channel, ...)
        local results = pack(fn(self, sender, channel, ...))
        local current = controller(state, self._is_server)
        if current then
            for level_id in pairs(current.removed_stations) do
                RPC.rpc_health_station_despawn(channel, level_id)
            end
        end
        return unpack(results, 1, results.n)
    end)

    mod:hook(PickupSystem, "spawn_pickup", function(fn, self, name, ...)
        local current = controller(state, self._is_server)
        if current and current.transfer_depth == 0 and blocked_pickups[name] then
            return nil, nil
        end
        return fn(self, name, ...)
    end)

    -- Dropping/swapping an already carried item is not a new map supply.
    -- These native callers also expect a real returned unit for bookkeeping.
    mod:hook(PickupSystem, "player_spawn_pickup", function(fn, self, ...)
        local current = controller(state, self._is_server)
        if current then return transfer(current, fn, self, ...) end
        return fn(self, ...)
    end)
    for _,method in ipairs({ "drop_pocketable", "equip_pocketable" }) do
        mod:hook(Pocketable, method, function(fn, ...)
            local current = controller(state)
            if current then return transfer(current, fn, ...) end
            return fn(...)
        end)
    end
    return state
end

local function system(name)
    local extension = Managers.state and Managers.state.extension
    if extension and extension:has_system(name) then return extension:system(name) end
end

local function new_controller()
    local current = {
        active = true,
        session = Managers.state.game_session,
        decisions = setmetatable({}, { __mode = "k" }),
        cleared = setmetatable({}, { __mode = "k" }),
        pending = {},
        removed_stations = {},
        transfer_depth = 0,
        scanned_pickups = nil,
        scanned_stations = nil,
    }

    function current:station_kind(extension)
        local known = self.decisions[extension]
        if known then return known end
        local plugged
        if extension._first_frame_setup then
            plugged = extension:battery_in_slot()
        else
            -- Match the native first-frame placement decision, before zeroing
            -- its charge count. A full distribution can intentionally be loose.
            local mode = extension:battery_spawning_mode()
            plugged = mode == "plugged"
            if extension:use_distribution_pool() then
                plugged = mode == "plugged_with_charge" and extension._plug_from_distribution
            end
            local circumstance = Managers.state.circumstance
            local overrides = circumstance and circumstance:mission_overrides().health_station
            if overrides and overrides.skip_battery_spawning then plugged = false end
        end
        local decision = plugged and "keep" or "remove"
        self.decisions[extension] = decision
        return decision
    end

    function current:empty_station(extension)
        extension._distributed_charges = 0
        if extension:charge_amount() ~= 0 then
            extension:set_charge_amount(0)
            extension:sync_charge_amount()
            if extension:battery_in_slot() then extension:play_anim("close") end
        else
            -- Native socketing may already have synchronized zero. This call
            -- keeps late activation consistent without changing battery state.
            extension:sync_charge_amount()
        end
        self.cleared[extension] = true
    end

    function current:scan_existing()
        local stations = system("health_station_system")
        if stations and stations._is_server and self.scanned_stations ~= stations then
            self.scanned_stations = stations
            for unit, extension in pairs(stations:unit_to_extension_map()) do
                -- Uninitialized distribution fields are not a placement result.
                -- The first fixed update handles stations still being set up.
                if ALIVE[unit] and extension._first_frame_setup then
                    if self:station_kind(extension) == "keep" then self:empty_station(extension)
                    else self.pending[unit] = extension end
                end
            end
        end
        local pickups = system("pickup_system")
        if pickups and pickups._is_server and self.scanned_pickups ~= pickups then
            self.scanned_pickups = pickups
            local remove = {}
            for _,unit in ipairs(pickups._spawned_pickups) do
                if ALIVE[unit] and not pickups._dropped_pickups[unit]
                    and not pickups._pickup_to_owner_player[unit]
                    and blocked_pickups[Unit.get_data(unit, "pickup_type")] then
                    remove[#remove + 1] = unit
                end
            end
            for _,unit in ipairs(remove) do pickups:despawn_pickup(unit) end
        end
    end

    function current:remove_pending()
        local spawner = Managers.state.unit_spawner
        if not spawner then return end
        for unit, extension in pairs(self.pending) do
            if ALIVE[unit] then
                -- This is the station's own tracked battery, never every
                -- battery_01/battery_02 pickup used by other mission objectives.
                extension:unspawn_battery()
                local level_id = spawner:level_index(unit)
                if level_id and not self.removed_stations[level_id] then
                    Managers.state.game_session:send_rpc_clients("rpc_health_station_despawn", level_id)
                    self.removed_stations[level_id] = true
                end
                if not spawner:is_marked_for_deletion(unit) then spawner:mark_for_deletion(unit) end
            end
            self.pending[unit] = nil
        end
    end
    return current
end

return {
    api_version = { major = 1, minor = 0 },
    entries = {
        no_healing = {
            interval = 0.1,
            on_activate = function(ctx)
                local hooks = install_hooks()
                local current = new_controller()
                hooks.current = current
                ctx.state.current = current
                ctx:on_cleanup(function()
                    current.active = false
                    if hooks.current == current then hooks.current = nil end
                    current.pending = {}
                    ctx.state.current = nil
                end)
                current:scan_existing()
                current:remove_pending()
            end,
            on_update = function(ctx)
                local current = ctx.state.current
                if not current or not current.active or not mod.has_local_gameplay_authority()
                    or Managers.state.game_session ~= current.session then return end
                current:scan_existing()
                current:remove_pending()
            end,
        },
    },
}
]=],
    },
}
